-- CREATE TABLE nba_players (
--     PERSON_ID INT,
--     PLAYER_LAST_NAME VARCHAR(50),
--     PLAYER_FIRST_NAME VARCHAR(50),
--     PLAYER_SLUG VARCHAR(50),
--     TEAM_ID BIGINT,
--     TEAM_SLUG VARCHAR(50),
--     IS_DEFUNCT INT,
--     TEAM_CITY VARCHAR(50),
--     TEAM_NAME VARCHAR(50),
--     TEAM_ABBREVIATION VARCHAR(10),
--     JERSEY_NUMBER VARCHAR(10),
--     POSITION VARCHAR(20),
--     HEIGHT VARCHAR(10),
--     WGT FLOAT,
--     COLLEGE VARCHAR(100),
--     COUNTRY VARCHAR(50),
--     DRAFT_YEAR FLOAT,
--     DRAFT_ROUND FLOAT,
--     DRAFT_NUMBER FLOAT,
--     ROSTER_STATUS FLOAT,
--     PTS FLOAT,
--     REB FLOAT,
--     AST FLOAT,
--     STATS_TIMEFRAMR VARCHAR(20),
--     FROM_YEAR INT,
--     TO_YEAR INT
-- );

-- SELECT ALL COLUMNS FROM THE INDEX TABLE
SELECT * FROM PlayerIndex_nba_stats

-- TOP 20 SCORERS IN NBA HISTORY
SELECT TOP 20 PLAYER_FIRST_NAME + ' ' + PLAYER_LAST_NAME AS Player, PTS AS Points 
FROM PlayerIndex_nba_stats
ORDER BY Points DESC;

-- AVERAGE STATS BY POSITION
SELECT POSITION,
        ROUND(AVG(PTS), 2) AS Avg_PTS,
        ROUND(AVG(REB), 2) AS Avg_REB,
        ROUND(AVG(AST), 2) AS Avg_AST
FROM PlayerIndex_nba_stats
WHERE POSITION IS NOT NULL 
GROUP BY POSITION;

-- COLLEGE WITH MOST NBA PLAYERS
SELECT COLLEGE, COUNT(*) AS TotalPlayers
FROM PlayerIndex_nba_stats
WHERE COLLEGE IS NOT NULL AND COLLEGE <> ''
GROUP BY COLLEGE
ORDER BY TotalPlayers DESC;

-- DRAFT TRENDS OVER TIME
SELECT DRAFT_YEAR, COUNT(*) AS DraftedPlayers
FROM PlayerIndex_nba_stats
WHERE DRAFT_YEAR IS NOT NULL
GROUP BY DRAFT_YEAR
ORDER BY DraftedPlayers DESC;

-- PLAYERS WHO AVERAGED 20+ POINTS
SELECT PLAYER_FIRST_NAME + ' ' + PLAYER_LAST_NAME AS Player, PTS AS Points
FROM PlayerIndex_nba_stats
WHERE PTS >= 20
ORDER BY PTS DESC;

-- HEIGHT DISTRIBUTION (500 players are 6ft 7inches tall which is the most common height)
SELECT HEIGHT, COUNT(*) AS CountByHeight
FROM PlayerIndex_nba_stats
GROUP BY HEIGHT
ORDER BY CountByHeight DESC;

-- NUMBER OF PLAYERS BY POSITION
SELECT POSITION, COUNT(*) AS PlayerCount
FROM PlayerIndex_nba_stats
GROUP BY POSITION
ORDER BY PlayerCount DESC;